apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporting
  namespace: ledger-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: ledger-api
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      serviceAccountName: reporting
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: client
          image: curlimages/curl:8.8.0
          command: ["sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
---

apiVersion: v1
kind: Service
metadata:
  name: reporting
  namespace: ledger-api 
spec:
  selector:
    app: reporting
  ports:
    - port: 9080
      targetPort: 9080